CREATE TABLE users(
    NAME TEXT,
    EMAIL TEXT PRIMARY KEY,
    PASSWORD TEXT
)

CREATE TABLE follows(
    ID INTEGER PRIMARY KEY,
    EMAIL INTEGER,
    MARKET_HASH_NAME TEXT
)

CREATE TABLE items(
    ASSET_ID INTEGER PRIMARY KEY,
    MARKET_HASH_NAME TEXT NOT NULL,
    PRICE INTEGER NOT NULL,
    APPID INTEGER NOT NULL,
    TIME INTEGER NOT NULL,
    IMAGE TEXT NOT NULL
)
