CREATE TABLE users(
    NAME TEXT,
    EMAIL TEXT PRIMARY KEY,
    PASSWORD TEXT
)

CREATE TABLE follows(
    ID INTEGER PRIMARY KEY,
    EMAIL TEXT NOT NULL,
    MARKET_HASH_NAME TEXT NOT NULL
)

CREATE TABLE items(
    ASSET_ID INTEGER PRIMARY KEY,
    MARKET_HASH_NAME TEXT NOT NULL,
    PRICE INTEGER NOT NULL,
    APPID INTEGER NOT NULL,
    TIME INTEGER NOT NULL,
    IMAGE TEXT NOT NULL
)

CREATE TABLE notifications(
    ID INTEGER PRIMARY KEY,
    ASSET_ID INTEGER NOT NULL,
    EMAIL TEXT NOT NULL
)
