CREATE TABLE users(
    NAME TEXT,
    EMAIL TEXT PRIMARY KEY,
    PASSWORD TEXT
)

CREATE TABLE follows(
    ID NUMBER PRIMARY KEY,
    EMAIL NUMBER,
    MARKET_HASH_NAME TEXT
)

CREATE TABLE items(
    ASSET_ID NUMBER PRIMARY KEY,
    MARKET_HASH_NAME TEXT,
    PRICE NUMBER,
    TIME NUMBER
)
