// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package custSql

import (
	"database/sql"
)

type Follow struct {
	ID             int64
	Email          string
	MarketHashName string
}

type Item struct {
	AssetID        int64
	MarketHashName string
	Price          int64
	Appid          int64
	Time           int64
	Image          string
}

type Notification struct {
	ID      int64
	AssetID int64
	Email   string
}

type User struct {
	Name     sql.NullString
	Email    string
	Password sql.NullString
}
