// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package custSql

import (
	"context"
)

const get_All_Users = `-- name: Get_All_Users :many
SELECT
    uid, name, email, password
FROM
    USERS
`

func (q *Queries) Get_All_Users(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, get_All_Users)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Name,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
